### ISSUE TITLE
Implementing custom load-render function

### ISSUE THREAD

**Issue by dbjergaard** [rpav/cl-freetype2#5]
Hi,

I'm trying to implement a cache for the load-render in order to improve rendering speed.  The full implementation is here:
https://github.com/dbjergaard/clx-ft2-renderer/blob/master/render.lisp

If your inclined to try to run the code, check it out to ${HOME}/quicklisp/local-projects/ and quickload it, then run `(clx-freetype2-renderer:render-test)`, the code will fail with:

```
:NONE fell through ECASE expression.
Wanted one of (:LCD-V :LCD :GRAY :MONO).
   [Condition of type SB-KERNEL:CASE-FAILURE]

Restarts:
 0: [RETRY] Retry SLIME REPL evaluation request.
 1: [*ABORT] Return to SLIME's top level.
 2: [ABORT] Abort thread (#<THREAD "repl-thread" RUNNING {1003EB0083}>)

Backtrace:
  0: (SB-KERNEL:CASE-FAILURE ECASE :NONE (:LCD-V :LCD :GRAY :MONO))
  1: (FREETYPE2:BITMAP-TO-ARRAY #<FREETYPE2-TYPES:FT-BITMAP {#X7FFFF0009978}>)
  2: (CLX-FREETYPE2-RENDERER::STRING-TO-ARRAY #<FREETYPE2-TYPES:FT-FACE "DejaVu Sans Oblique" {#x7FFFF000D520}> "⚡" :LEFT-RIGHT 11 19)
```

My load-render function looks like:

``` lisp
(defun load-render (face char vertical-p)
  (ft2:load-char face char (if vertical-p '(:vertical-layout) '(:default)))
  (let ((char-list (cache-char face char vertical-p *ft2-face-cache*)))
    (when char-list
      (values (aref char-list 0)
          (aref char-list 1)
          (aref char-list 2)
          (aref char-list 3)))))
```

cache-char is a wrapper of default-load-render that first checks if the char has been cached in `*ft2-face-cache*`

Could you give me any hints on how to correctly implement this method?

**Comment by dbjergaard** [comment]
Hi,

Sorry for taking so long to try to implement this.  I tried putting ft2:bitmap-to-array in place of the bitmap in my load-render function.  This didn't work.  Inspecting your example code isn't leading to any insights.  It looks like your (new ... ) code makes an instance of an object that knows how to copy from a pointer to the bitmap buffer.  I tried to use ft2::ft-bitmap-copy into a variable instance of ft2::bitmap-new, but this doesn't work because my bitmap isn't a "sb-sys:system-area-pointer".  Thanks for any further hints.

**Comment by dbjergaard** [comment]
Sorry for the noise, I may be figuring it out.  I think I should be able to use cffi:mem-* functions to extract and copy the data into a new bitmap array.

**Comment by rpav** [comment]
Yeah, you will need to extract the data somehow; however all the values you should be required to store and/or how they are extracted should be present.  Notable as I recall were bit ordering and stride handling, but the details escape me.

If you can get something visible to start (print the bits or somesuch), you'll have a useful reference.

**Comment by dbjergaard** [comment]
I finally got the cache working properly.  Thanks for the pointers!
